#!/bin/bash
while :
do
    clear
    # git --no-pager log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ci) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative --all
    git --no-pager logtree
    sleep 1
done
